---
apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: helloworld
  name: helloworld-dc
spec:
  replicas: 2
  selector:
    app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/scheme: http
        prometheus.io/path: /actuator/metrics
        prometheus.io/port: "8080"
    spec:
      containers:
        - image: helloworld:v1
          imagePullPolicy: IfNotPresent
          resources: {}
          name: helloworld-c
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - helloworld-c
        from:
          kind: ImageStreamTag
          name: 'helloworld:v1'
      type: ImageChange

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: helloworld
  name: helloworld-svc
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: helloworld
  sessionAffinity: None
  type: ClusterIP

---
apiVersion: v1
kind: Route
metadata:
  labels:
    app: helloworld
  name: helloworld-route
spec:
  to:
    kind: Service
    name: helloworld-svc
    weight: 100
  wildcardPolicy: None
